CREATE DATABASE data_tienda;
USE data_tienda;

CREATE TABLE LOGIN (
 _code INT NOT NULL AUTO_INCREMENT,
 user_name VARCHAR(100) NOT NULL UNIQUE,
 _password VARCHAR(150) NOT NULL,
 _type VARCHAR(50) NOT NULL,
 state varchar(50) NOT NULL,
 PRIMARY KEY (_code)
);

CREATE TABLE USER_ADMIN(
_code INT NOT NULL,
_name VARCHAR(100) UNIQUE NOT NULL,
user_name VARCHAR(100) NOT NULL,
_password VARCHAR(150) NOT NULL,
PRIMARY KEY(_code,_name),
FOREIGN KEY (_code, user_name, _password) REFERENCES LOGIN(_code) ON UPDATE CASCADE
);

CREATE TABLE CATALOGUE(
_code INT NOT NULL AUTO_INCREMENT,
_name VARCHAR(100) NOT NULL,
cost DECIMAL(9,2) NOT NULL,
price DECIMAL(9.2) NOT NULL,
existence INT NOT NULL,
PRIMARY KEY (_code)
);

CREATE TABLE STORE(
_code INT NOT NULL AUTO_INCREMENT,
address VARCHAR(150) NOT NULL,
_type VARCHAR(100) NOT NULL,
PRIMARY KEY (_code)
);

CREATE TABLE USER_STORE(
_Code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
store INT NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR(100) NOT NULL,
PRIMARY KEY(_code),
FOREIGN KEY(_code) REFERENCES LOGIN(_code) ON UPDATE CASCADE
);

CREATE TABLE STORE_CATALOGUE(
code_catalogue INT NOT NULL,
code_store INT NOT NULL,
existences INT NOT NULL,
FOREIGN KEY(code_catalogue) REFERENCES CATALOGUE(_code) ON UPDATE CASCADE, 
FOREIGN KEY(code_store) REFERENCES STORE(_code) ON UPDATE CASCADE
); 

CREATE TABLE SUPERVISORY(
_code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR (100),
PRIMARY KEY(_code),
FOREIGN KEY(_code)  REFERENCES LOGIN(_code) ON UPDATE CASCADE
);

