CREATE DATABASE data_tienda;
USE data_tienda;

CREATE TABLE LOGIN (
 _code INT NOT NULL AUTO_INCREMENT,
 user_name VARCHAR(100) NOT NULL UNIQUE,
 _password VARCHAR(150) NOT NULL,
 _type VARCHAR(50) NOT NULL,
 state varchar(50) NOT NULL,
 PRIMARY KEY (_code)
);

CREATE TABLE USER_ADMIN(
_code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
user_name VARCHAR(100) NOT NULL UNIQUE,
_password VARCHAR(150) NOT NULL,
PRIMARY KEY(_code),
FOREIGN KEY (_code) REFERENCES LOGIN(_code) ON UPDATE CASCADE
);
Insert into login value(1,'admin','8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918','ADMINISTRADOR','ACTIVADO');
insert into user_admin value(1,'admin','admin','8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');

CREATE TABLE CATALOGUE(
_code INT NOT NULL AUTO_INCREMENT,
_name VARCHAR(100) NOT NULL,
cost DECIMAL(9,2) NOT NULL,
price DECIMAL(9,2) NOT NULL,
existence INT NOT NULL,
PRIMARY KEY (_code)
);

CREATE TABLE STORE(
_code INT NOT NULL AUTO_INCREMENT,
address VARCHAR(150) NOT NULL,
_type VARCHAR(100) NOT NULL,
PRIMARY KEY (_code)
);

CREATE TABLE TIENDA_PRODUCTO(
codigo_tienda INT NOT NULL,
codigo_producto INT NOT NULL,
existencia INT NOT NULL,
PRIMARY KEY(codigo_tienda, codigo_producto),
FOREIGN KEY(codigo_tienda) REFERENCES STORE (_code) ON UPDATE CASCADE
);

CREATE TABLE USER_STORE(
_Code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
store INT NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR(100) NOT NULL,
PRIMARY KEY(_code),
FOREIGN KEY(_code) REFERENCES LOGIN(_code) ON UPDATE CASCADE,
FOREIGN KEY(store) REFERENCES STORE(_code)ON UPDATE CASCADE
);

CREATE TABLE SUPERVISORY(
_code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR (100),
PRIMARY KEY(_code),
FOREIGN KEY(_code)  REFERENCES LOGIN(_code) ON UPDATE CASCADE
);
CREATE TABLE WAREHOUSE (
_code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR (100),
PRIMARY KEY(_code),
FOREIGN KEY(_code)  REFERENCES LOGIN(_code) ON UPDATE CASCADE
); 

CREATE TABLE listaTiendaBodega(
_Code INT NOT NULL,
tienda INT NOT NULL,
primary key(_code, tienda),
FOREIGN KEY(tienda) REFERENCES STORE(_code) ON UPDATE CASCADE
);

CREATE TABLE PEDIDO(
 id INT NOT NULL AUTO_INCREMENT,
 tienda INT NOT NULL,
 codigo_usuario INT NOT NULL,
 fecha DATE NOT NULL,
 total Decimal(9,2)  NOT NULL,
 estado VARCHAR(100) NOT NULL,
 PRIMARY KEY( id),
FOREIGN KEY(codigo_usuario) REFERENCES  USER_STORE (_code) ON UPDATE CASCADE,
FOREIGN KEY(tienda) REFERENCES STORE(_code) ON UPDATE CASCADE

);

CREATE TABLE PEDIDOS_PRODUCTOS(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
costoU  DECIMAL(9,2) NOT NULL,
cantidad INT NOT NULL,
costoTotal DECIMAL(9,2) NOT NULL,
PRIMARY KEY(id_pedido, codigo),
FOREIGN KEY(id_pedido) REFERENCES PEDIDO (id) ON UPDATE CASCADE
);

CREATE TABLE ENVIOS(
 id_envio INT NOT NULL AUTO_INCREMENT,
 id INT NOT NULL,
 tienda INT NOT NULL,
 codigo_usuario INT NOT NULL,
 fechaSalida DATE NOT NULL,
 fechaRecibido DATE,
 total DECIMAL(9,2) NOT NULL,
 estado VARCHAR(100) NOT NULL,
 PRIMARY KEY(id_envio,id),
FOREIGN KEY(codigo_usuario) REFERENCES  WAREHOUSE (_code) ON UPDATE CASCADE,
FOREIGN KEY(tienda) REFERENCES STORE(_code) ON UPDATE CASCADE
);

CREATE TABLE ENVIOS_PRODUCTOS(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
costoU  DECIMAL(9,2) NOT NULL,
cantidad INT NOT NULL,
costoTotal DECIMAL(9,2) NOT NULL,
PRIMARY KEY(id_pedido, codigo)
);

CREATE TABLE INCIDENCIAS(
id_incidencia INT NOT NULL AUTO_INCREMENT,
id INT NOT NULL,
tienda INT NOT NULL,
codigo_usuario INT NOT NULL,
fecha DATE NOT NULL,
solucion  text NOT NULL,
estado VARCHAR(100) NOT NULL,
PRIMARY KEY(id_incidencia,id),
FOREIGN KEY(codigo_usuario) REFERENCES  USER_STORE (_code) ON UPDATE CASCADE,
FOREIGN KEY(tienda) REFERENCES STORE(_code) ON UPDATE CASCADE
);

CREATE TABLE INCIDENCIAS_PRODUCTO(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
cantidad INT NOT NULL,
motivo VARCHAR(100) NOT NULL,
PRIMARY KEY(id_pedido, codigo)
);

CREATE TABLE DEVOLUCIONES(
id_devoluciones INT NOT NULL AUTO_INCREMENT,
id INT NOT NULL,
tienda INT NOT NULL,
codigo_usuario INT NOT NULL,
fecha DATE NOT NULL,
total  DECIMAL(9,2) NOT NULL,
estado VARCHAR(100) NOT NULL,
PRIMARY KEY(id_devoluciones,id),
FOREIGN KEY(codigo_usuario) REFERENCES  USER_STORE (_code) ON UPDATE CASCADE,
FOREIGN KEY(tienda) REFERENCES STORE(_code) ON UPDATE CASCADE
);

CREATE TABLE DEVOLUCIONES_PRODUCTO(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
costo DECIMAL(9,2) NOT NULL,
cantida INT NOT NULL,
costoTotal DECIMAL(9,2),
motivo VARCHAR(100) NOT NULL,
PRIMARY KEY(id_pedido, codigo)
);








