CREATE DATABASE data_tienda;
USE data_tienda;

CREATE TABLE LOGIN (
 _code INT NOT NULL AUTO_INCREMENT,
 user_name VARCHAR(100) NOT NULL UNIQUE,
 _password VARCHAR(150) NOT NULL,
 _type VARCHAR(50) NOT NULL,
 state varchar(50) NOT NULL,
 PRIMARY KEY (_code)
);

CREATE TABLE USER_ADMIN(
_code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
user_name VARCHAR(100) NOT NULL UNIQUE,
_password VARCHAR(150) NOT NULL,
PRIMARY KEY(_code),
FOREIGN KEY (_code) REFERENCES LOGIN(_code) ON UPDATE CASCADE
);

CREATE TABLE CATALOGUE(
_code INT NOT NULL AUTO_INCREMENT,
_name VARCHAR(100) NOT NULL,
cost DECIMAL(9,2) NOT NULL,
price DECIMAL(9,2) NOT NULL,
existence INT NOT NULL,
PRIMARY KEY (_code)
);

CREATE TABLE STORE(
_code INT NOT NULL AUTO_INCREMENT,
address VARCHAR(150) NOT NULL,
_type VARCHAR(100) NOT NULL,
PRIMARY KEY (_code)
);

CREATE TABLE TIENDA_PRODUCTO(
codigo_tienda INT NOT NULL,
codigo_producto INT NOT NULL,
existencia INT NOT NULL,
PRIMARY KEY(codigo_tienda, codigo_producto),
FOREIGN KEY(codigo_tienda) REFERENCES STORE (_code) ON UPDATE CASCADE
);

CREATE TABLE USER_STORE(
_Code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
store INT NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR(100) NOT NULL,
PRIMARY KEY(_code),
FOREIGN KEY(_code) REFERENCES LOGIN(_code) ON UPDATE CASCADE
);

CREATE TABLE STORE_CATALOGUE(
code_catalogue INT NOT NULL,
code_store INT NOT NULL,
existences INT NOT NULL,
FOREIGN KEY(code_catalogue) REFERENCES CATALOGUE(_code) ON UPDATE CASCADE, 
FOREIGN KEY(code_store) REFERENCES STORE(_code) ON UPDATE CASCADE
); 

CREATE TABLE SUPERVISORY(
_code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR (100),
PRIMARY KEY(_code),
FOREIGN KEY(_code)  REFERENCES LOGIN(_code) ON UPDATE CASCADE
);
CREATE TABLE WAREHOUSE (
_code INT NOT NULL,
_name VARCHAR(100) NOT NULL,
user_name VARCHAR(100) UNIQUE NOT NULL,
_password VARCHAR(150) NOT NULL,
email VARCHAR (100),
PRIMARY KEY(_code),
FOREIGN KEY(_code)  REFERENCES LOGIN(_code) ON UPDATE CASCADE
); 

CREATE TABLE listaTiendaBodega(
_Code INT NOT NULL,
tienda INT NOT NULL,
primary key(_code, tienda)
);

CREATE TABLE PEDIDO(
 id INT NOT NULL AUTO_INCREMENT,
 tienda INT NOT NULL,
 codigo_usuario INT NOT NULL,
 fecha DATE NOT NULL,
 total Decimal(9,2)  NOT NULL,
 estado VARCHAR(100) NOT NULL,
 PRIMARY KEY( id),
FOREIGN KEY(codigo_usuario) REFERENCES  USER_STORE (_code) ON UPDATE CASCADE
);

CREATE TABLE PEDIDOS_PRODUCTOS(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
costoU  DECIMAL(9,2) NOT NULL,
cantidad INT NOT NULL,
costoTotal DECIMAL(9,2) NOT NULL,
PRIMARY KEY(id_pedido, codigo),
FOREIGN KEY(id_pedido) REFERENCES PEDIDO (id) ON UPDATE CASCADE
);

CREATE TABLE ENVIOS(
 id INT NOT NULL AUTO_INCREMENT,
 tienda INT NOT NULL,
 codigo_usuario INT NOT NULL,
 fechaSalida DATE NOT NULL,
 fechaRecibido DATE NOT NULL,
 total DECIMAL(9,2) NOT NULL,
 estado VARCHAR(100) NOT NULL,
 PRIMARY KEY(id),
FOREIGN KEY(codigo_usuario) REFERENCES  WAREHOUSE (_code) ON UPDATE CASCADE
);

CREATE TABLE ENVIOS_PRODUCTOS(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
costoU  DECIMAL(9,2) NOT NULL,
cantidad INT NOT NULL,
costoTotal DECIMAL(9,2) NOT NULL,
PRIMARY KEY(id_pedido, codigo),
FOREIGN KEY(id_pedido) REFERENCES ENVIOS (id) ON UPDATE CASCADE
);

CREATE TABLE INCIDENCIAS(
id INT NOT NULL AUTO_INCREMENT,
tienda INT NOT NULL,
codigo_usuario INT NOT NULL,
fecha DATE NOT NULL,
solucion  VARCHAR(100) NOT NULL,
estado VARCHAR(100) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(codigo_usuario) REFERENCES  USER_STORE (_code) ON UPDATE CASCADE
);

CREATE TABLE INCIDENCIAS_PRODUCTO(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
cantidad INT NOT NULL,
motivo VARCHAR(100) NOT NULL,
PRIMARY KEY(id_pedido, codigo),
FOREIGN KEY(id_pedido) REFERENCES INCIDENCIAS (id) ON UPDATE CASCADE
);

CREATE TABLE DEVOLUCIONES(
id INT NOT NULL AUTO_INCREMENT,
tienda INT NOT NULL,
codigo_usuario INT NOT NULL,
fecha DATE NOT NULL,
total  DECIMAL(9,2) NOT NULL,
estado VARCHAR(100) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(codigo_usuario) REFERENCES  USER_STORE (_code) ON UPDATE CASCADE
);

CREATE TABLE DEVOLUCIONES_PRODUCTO(
id_pedido INT NOT NULL,
codigo INT NOT NULL,
costo DECIMAL(9,2) NOT NULL,
cantida INT NOT NULL,
costoTotal DECIMAL(9,2),
motivo VARCHAR(100) NOT NULL,
PRIMARY KEY(id_pedido, codigo),
FOREIGN KEY(id_pedido) REFERENCES DEVOLUCIONES (id) ON UPDATE CASCADE
);








